workspace:
  base: /go
  path: src/github.com/metalmatze/time.kitchen

pipeline:
  build:
    group: go
    image: golang:1.9
    pull: true
    commands:
    - go get -v ./...
    - CGO_ENABLED=0 go build -v -ldflags '-w -extldflags "-static"'
    when:
      event: [ push, tag, pull_request ]

  docker:
    image: plugins/docker
    repo: metalmatze/time.kitchen
    secrets: [ docker_username, docker_password ]
    tags:
      - 'latest'
    when:
      branch: master
